### ISSUE TITLE
Decorators are not marked as used

### ISSUE THREAD

**Issue by unlight** [nzakas/eslint-plugin-typescript#18] opened 2017-01-11 11:04 UTC
```ts
import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: require("./app.component.html"),
})
export class AppComponent {
    name = 'Angular';
}
```
```
src\app.component.ts
  1:10  error  'Component' is defined but never used  no-unused-vars
```

**Comment by NeoReyad** [comment] 2017-01-12 15:11
This has been mentioned in issue https://github.com/eslint/typescript-eslint-parser/issues/77. I believe we would have to modify the eslint rule itself to better accommodate decorators.

**Comment by weirdpattern** [comment] 2017-01-12 16:34
This might be a duplicate of #2 
There is some work already done (#3 and #9)

**Comment by NeoReyad** [comment] 2017-01-12 17:01
Does this mean  the rule "typescript/no-unused-vars" has to be enabled for interfaces and decorators to be marked as used? Am I reading https://github.com/nzakas/eslint-plugin-typescript/pull/9 correctly?

**Comment by weirdpattern** [comment] 2017-01-12 19:30
you just need to include the plugin and the original ESlint "no-unused-vars" rule.  

1. 
![1](https://cloud.githubusercontent.com/assets/19519411/21904963/34dc13ea-d8cb-11e6-9a63-801720d6c1e3.png)

2. 
![2](https://cloud.githubusercontent.com/assets/19519411/21904964/34dc6930-d8cb-11e6-8811-4a5d40e395f4.png)

3. 
![3](https://cloud.githubusercontent.com/assets/19519411/21904961/34d8e9fe-d8cb-11e6-908e-76d59c454737.png)

4. 
![4](https://cloud.githubusercontent.com/assets/19519411/21904962/34dbbdfa-d8cb-11e6-8c66-b3e00bd192d0.png)

**Comment by weirdpattern** [comment] 2017-01-12 19:35
you just need to include the plugin and the original ESlint "no-unused-vars" rule.  

1.
![1](https://cloud.githubusercontent.com/assets/19519411/21905121/fed560f2-d8cb-11e6-8c3b-921d17c2c678.png)

2.
![2](https://cloud.githubusercontent.com/assets/19519411/21905123/fedbc38e-d8cb-11e6-9a66-80fb34832340.png)

3.
![3](https://cloud.githubusercontent.com/assets/19519411/21905122/fed982ea-d8cb-11e6-899a-d94db613055a.png)

4.
![4](https://cloud.githubusercontent.com/assets/19519411/21905120/fed4dbfa-d8cb-11e6-85ae-c5385849120d.png)

**Comment by NeoReyad** [comment] 2017-01-12 19:56
Thanks @weirdpattern. I can confirm it works with the typescript/no-undef-vars rule. The version in npm is quite old and should be updated. I had to tell npm to pull from master to get it to work.

npm install git+https://github.com/nzakas/eslint-plugin-typescript.git

**Comment by JamesHenry** [comment] 2017-01-14 17:15
Sorry about that @NeoReyad, we'll look to get a release out once the latest PRs go in!

**Comment by JamesHenry** [comment] 2017-07-11 11:42
There are a couple of different workarounds for this, as previously referenced, and I have just released the latest work to npm, so I am going to close this.

**Closed by JamesHenry** 2017-07-11 11:42 UTC
